### ISSUE TITLE
Question regarding image with child image and Shiny UI

### ISSUE THREAD

**Issue by ColorTwist** [mob-sakai/ShinyEffectForUGUI#21]
Hello,

Very cool asset :)

I was wondering, i have this blank button image and as a child i place an icon image.
```
[Blank button image] - Parent
         [Icon Image] - Child
```

If i apply Shiny UI to parent, obviously it will not affect the child icon image.

Is there a way to allow Parent Shiny UI effect all image children or at least one child?

**Comment by ColorTwist** [comment]
I am using UIEffect, i think i should have asked it there?
https://github.com/mob-sakai/UIEffect

**Comment by mob-sakai** [comment]
Hi @ColorTwist 

That's a good feature request!

>I am using UIEffect, i think i should have asked it there?
https://github.com/mob-sakai/UIEffect

Yes.
Sorry to bother you but please create the issue in UIEffect.

**Comment by ColorTwist** [comment]
Done, you can close/delete this 1

**Comment by mob-sakai** [comment]
Thanks a lot!
